"""financings

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 00:03:03.265052
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("LOAN", "BUILDING_SAVINGS", name="financingkind", native_enum=False, length=24),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financings_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "financing_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("financing_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["financing_id"],
            ["financings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financing_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financing_events_financing_id"), ["financing_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("financing_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financing_events_financing_id"))

    op.drop_table("financing_events")
    with op.batch_alter_table("financings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financings_household_id"))

    op.drop_table("financings")
    # ### end Alembic commands ###
