"""depot

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 00:19:12.587709
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ETF', 'PRIVATE_EQUITY', name='instrumentkind', native_enum=False, length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('expected_return_percent', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('cost_percent', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('entry_fee_percent', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('start_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_household_id'), ['household_id'], unique=False)

    op.create_table('one_off_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('one_off_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_off_payments_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('savings_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_rates_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_rates_instrument_id'))

    op.drop_table('savings_rates')
    with op.batch_alter_table('one_off_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_one_off_payments_instrument_id'))

    op.drop_table('one_off_payments')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_household_id'))

    op.drop_table('instruments')
    # ### end Alembic commands ###
