"""catalog

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 00:27:39.798180
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("index_name", sa.String(length=80), nullable=True),
        sa.Column("ter_percent", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("distribution", sa.String(length=24), nullable=True),
        sa.Column("replication", sa.String(length=32), nullable=True),
        sa.Column("domicile", sa.String(length=40), nullable=True),
        sa.Column("fund_size_m_eur", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("as_of", sa.String(length=7), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("catalog_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catalog_entries_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_catalog_entries_isin"), ["isin"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_entries_isin"))
        batch_op.drop_index(batch_op.f("ix_catalog_entries_household_id"))

    op.drop_table("catalog_entries")
    # ### end Alembic commands ###
