"""actuals

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 00:53:49.177730
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actual_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "month"),
    )
    with op.batch_alter_table("actual_values", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_actual_values_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "depot_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("shares", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "external_id"),
    )
    with op.batch_alter_table("depot_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_depot_transactions_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_depot_transactions_instrument_id"), ["instrument_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("depot_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_depot_transactions_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_depot_transactions_household_id"))

    op.drop_table("depot_transactions")
    with op.batch_alter_table("actual_values", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_actual_values_instrument_id"))

    op.drop_table("actual_values")
    # ### end Alembic commands ###
